name: aponwola
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+4

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  intl: ^0.18.0
  form_field_validator: ^1.1.0
  material_design_icons_flutter: ^6.0.7096
  shared_preferences: ^2.0.11
  cached_network_image: ^3.3.0
  lazy_load_scrollview: ^1.3.0
  shimmer: ^2.0.0
  image_cropper: ^3.0.1
  image_picker: ^0.8.4+8 #inuse
  font_awesome_flutter: ^10.1.0

  flutter_local_notifications: ^9.3.0
  share_plus: ^6.3.1

  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  responsive_grid: ^2.1.0
  animations: ^2.0.7
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  url_launcher: ^6.1.5
  firebase_auth: ^4.6.3
  whatsapp_unilink: ^2.1.0

  iconsax: 0.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5  #
  get: ^4.6.5

#  flutter_native_splash: ^2.2.16
#  path: ^1.8.3
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_native_splash:
#  image: "assets/apon.png"
#  color: "#f9f9f9"
#  android: false
#  ios: false
#  web: false
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - .env
    - assets/
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratRomanExtraBold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Euclid Circular B
      fonts:
        - asset: assets/fonts/EuclidCircularBRegular.ttf
          weight: 400